#spring:
##  datasource:
##    url: jdbc:h2:tcp://localhost/~/notice-msa
##    username: sa
##    password:
##    driver-class-name: org.h2.Driver
##  jpa:
##    hibernate:
##      ddl-auto: create
##    properties:
##      hibernate:
##        # show_sql: true
##        format_sql: true
##logging.level:
##  org.hibernate.SQL: debug
##  org.hibernate.type: trace
spring:
  rabbitmq:
    host: localhost # RabbitMQ host ip
    port: 5672 # RabbitMQ port
    username : guest # RabbitMQ 웹 관리 콘솔 아이디
    password: guest # RabbitMQ 웹 관리 콘솔 비밀번호

rabbitmq:
  queue:
    name: sample-queue # 사용할 queue 이름
  exchange:
    name: sample-exchange # 사용할 exchange 이름
  routing:
    key : key

#jwt:
#  header: Authorization
##HS512알고리즘을 사용할 것이기 때문에 512bit,즉 64byte이상의 secret key를 사용해야 한다.
#  secret: c2lsdmVybmluZS10ZWsdfadgdsflgsfgdsfgdsfgdfsgdsfgdfgNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
#  token-validity-in-seconds: 86400000#만료기간 1일